FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /src
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/azure-functions/dotnet:2.0-iot-edge
WORKDIR /app

ENV AzureWebJobsScriptRoot=/app
ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true

EXPOSE 80/tcp

COPY --from=build-env /src/out/ .
