FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore src/Publisher.csproj
RUN dotnet publish src/Publisher.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:2.1-alpine3.7
WORKDIR /app
COPY --from=build-env /app/src/out/ .

CMD ["dotnet", "aegp.dll"]